<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-7I57STG" ignored="0" name="Default test" tests="1" failures="1" timestamp="15 Jul 2022 12:54:06 GMT" time="9.155" errors="0">
  <testcase name="Login" time="9.031" classname="com.test.OMRBranchClub">
    <failure type="java.lang.RuntimeException" message="com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field &amp;quot;exception&amp;quot; (class com.pojo.Login_Output_pojo), not marked as ignorable (6 known properties: &amp;quot;cart_count&amp;quot;, &amp;quot;status&amp;quot;, &amp;quot;role&amp;quot;, &amp;quot;message&amp;quot;, &amp;quot;data&amp;quot;, &amp;quot;refer_msg&amp;quot;])
 at [Source: (String)&amp;quot;{
    &amp;quot;message&amp;quot;: &amp;quot;Class &amp;apos;App\\Http\\Controllers\\BaseController&amp;apos; not found&amp;quot;,
    &amp;quot;exception&amp;quot;: &amp;quot;Symfony\\Component\\Debug\\Exception\\FatalThrowableError&amp;quot;,
    &amp;quot;file&amp;quot;: &amp;quot;/home/omrbranch/public_html/app/Http/Controllers/ApiController.php&amp;quot;,
    &amp;quot;line&amp;quot;: 106,
    &amp;quot;trace&amp;quot;: [
        {
            &amp;quot;file&amp;quot;: &amp;quot;/home/omrbranch/public_html/vendor/composer/ClassLoader.php&amp;quot;,
            &amp;quot;line&amp;quot;: 571,
            &amp;quot;function&amp;quot;: &amp;quot;include&amp;quot;
        },
        {
            &amp;quot;file&amp;quot;: &amp;quot;/home/omrbranch/public_html/vendor/co&amp;quot;[truncated 10900 chars]; line: 3, column: 19] (through reference chain: com.pojo.Login_Output_pojo[&amp;quot;exception&amp;quot;])">
      <![CDATA[java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "exception" (class com.pojo.Login_Output_pojo), not marked as ignorable (6 known properties: "cart_count", "status", "role", "message", "data", "refer_msg"])
 at [Source: (String)"{
    "message": "Class 'App\\Http\\Controllers\\BaseController' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/home/omrbranch/public_html/app/Http/Controllers/ApiController.php",
    "line": 106,
    "trace": [
        {
            "file": "/home/omrbranch/public_html/vendor/composer/ClassLoader.php",
            "line": 571,
            "function": "include"
        },
        {
            "file": "/home/omrbranch/public_html/vendor/co"[truncated 10900 chars]; line: 3, column: 19] (through reference chain: com.pojo.Login_Output_pojo["exception"])
	at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:30)
	at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
	at io.restassured.mapper.ObjectMapper$deserialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:254)
	at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
	at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:56)
	at io.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:231)
	at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:169)
	at com.test.OMRBranchClub.Login(OMRBranchClub.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "exception" (class com.pojo.Login_Output_pojo), not marked as ignorable (6 known properties: "cart_count", "status", "role", "message", "data", "refer_msg"])
 at [Source: (String)"{
    "message": "Class 'App\\Http\\Controllers\\BaseController' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/home/omrbranch/public_html/app/Http/Controllers/ApiController.php",
    "line": 106,
    "trace": [
        {
            "file": "/home/omrbranch/public_html/vendor/composer/ClassLoader.php",
            "line": 571,
            "function": "include"
        },
        {
            "file": "/home/omrbranch/public_html/vendor/co"[truncated 10900 chars]; line: 3, column: 19] (through reference chain: com.pojo.Login_Output_pojo["exception"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:28)
	... 46 more
]]>
    </failure>
  </testcase> <!-- Login -->
</testsuite> <!-- Default test -->
